### ISSUE TITLE
Cannot import DadataAsync

### ISSUE THREAD

**Issue by sa-ivannikov** [hflabs/dadata-py#1]
Im trying to use DadataAsync with Django, but i get an error: 
`ImportError: cannot import name 'DadataAsync'.`
What i did:
install package:
`pip install dadata`

Import package:
`from dadata import DadataAsync`

Start django server
`python manage.py runserver`

Importing the sync version of a client does not produce any errors and works as expected wtih import:

`from dadata import Dadata`

**Comment by nalgeon** [comment]
Please provide the full stack trace.

**Comment by sa-ivannikov** [comment]
Here:

`Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serg/Desktop/djangotz/bitz/bitz/urls.py", line 21, in <module>
    path('', include('lead.urls'))
  File "/home/serg/Desktop/djangotz/venv/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/serg/Desktop/djangotz/bitz/lead/urls.py", line 3, in <module>
    from . import views
  File "/home/serg/Desktop/djangotz/bitz/lead/views.py", line 6, in <module>
    from dadata import DadataAsync
ImportError: cannot import name 'DadataAsync'
`

**Comment by nalgeon** [comment]
And `pip freeze` output, please.

**Comment by sa-ivannikov** [comment]
> And `pip freeze` output, please.

asgiref==3.2.10
astroid==2.4.2
autopep8==1.5.4
bandit==1.6.2
certifi==2020.6.20
chardet==3.0.4
dadata==0.3.0
-e git+https://github.com/tigrus/dadata-python@614bc9a765d9401cef12b1b07364c1f98ea81c10#egg=dadata_client
Django==3.1
gitdb==4.0.5
GitPython==3.1.7
idna==2.10
importlib-metadata==1.7.0
isort==4.3.21
lazy-object-proxy==1.4.3
mccabe==0.6.1
pbr==5.4.5
pkg-resources==0.0.0
pycodestyle==2.6.0
pylint==2.5.3
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
six==1.15.0
smmap==3.0.4
sqlparse==0.3.1
stevedore==3.2.0
toml==0.10.1
typed-ast==1.4.1
urllib3==1.25.10
wrapt==1.12.1
zipp==3.1.0

**Comment by nalgeon** [comment]
You have an old version of `dadata` package (0.3.0). Current version is 20.7.0. Update it to solve the problem.
